### ISSUE TITLE
Amounts are strings, not floats

### ISSUE THREAD

**Issue by darynwilkinson** [shutupflanders/sensor.moneydashboard#1]
Hey. Great sensor. It's really nice to get everything into HA.

The one issue I am having is that the net amount is coming through as a string since it has a comma in the format eg 1,000.00. If I try to cast it to a float in a template it gives and error because of the comma: could not convert string to float: 'x,xxx.xx'

**Comment by shutupflanders** [comment]
Hi Daryn,
Thanks for checking it out!
There's 2 options to solve this:

1. I can provide a configuration option to ` "convert_to_float" ` which would pre-format the value for you
2. In your template, you could use the `replace` method like so: `{{ value.replace(",", "") }}` which would remove the comma.

The initial idea of this sensor was just to have it so it would automatically feed into lovelace without any additional configuration, but I'm happy to add it if enough people want it.

**Comment by darynwilkinson** [comment]
Thanks for the quick reply.

I would love the option to change it in the config if you have time. I don't think it should be a string to start with. It messes with my history for all my GBP sensors as it picks up a number like 1,000 as 1.

**Comment by shutupflanders** [comment]
> It messes with my history for all my GBP sensors as it picks up a number like 1,000 as 1

Fair point, I hadn't noticed that.
I'll set the default action to return as a float then put some documentation in on how to template it to have the comma for display purposes.

Won't take too long

**Comment by darynwilkinson** [comment]
Thanks a lot. Really appreciate it. Again, great sensor.

**Comment by shutupflanders** [comment]
Fixed in [https://github.com/shutupflanders/sensor.moneydashboard/releases/tag/1.0.2](1.0.2)

**Comment by shutupflanders** [comment]
@darynwilkinson should be fixed and available in HACS to update - let me know if you run into any more problems.
Thanks again.

**Comment by darynwilkinson** [comment]
Thanks. Just updated and that's looking good now.
